name: Build docker image and run tests

on:
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Access repo at $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Lint project
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      # Access repo at $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Build image and test
        run: docker build --tag levelup:${{ github.sha }} .
