name: Build and push dev image

on:
  push:
    branches:
    - main

jobs:
  build-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      # Access repo at $GITHUB_WORKSPACE
      - uses: actions/checkout@v2.3.4

      - name: DigitalOcean - setup doctl
        uses: digitalocean/action-doctl@v2.1.0
        with:
          token: ${{ secrets.DOCTL_TOKEN }}

      - name: Build dev docker image
        run: docker build -t ${{ secrets.DO_REPOSITORY }}/levelup-dev:${{ github.sha }} --target dev .

      - name: Push image to DO registry
        run: docker push ${{ secrets.DO_REPOSITORY }}/levelup-dev:${{ github.sha }}
