name: Build and push prod image

on:
  push:
    tags:
    - 'v*'

jobs:
  build-prod:
    runs-on: ubuntu-latest
    environment: prod

    env:
      IMAGE_NAME: ${{ secrets.DO_REPOSITORY }}/levelup

    steps:
      # Access repo at $GITHUB_WORKSPACE
      - uses: actions/checkout@v2.3.4

      - name: Get action reference name (branch, tag, etc)
        id: reference
        run: echo ::set-output name=ref::${GITHUB_REF#refs/*/}

      - name: DigitalOcean - setup doctl
        uses: digitalocean/action-doctl@v2.1.0
        with:
          token: ${{ secrets.DOCTL_TOKEN }}

      - name: Build prod docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ steps.reference.outputs.ref }} .

      - name: Push image to DO registry
        run: |
          doctl registry login --expiry-seconds 180
          docker push ${{ env.IMAGE_NAME }}:${{ steps.reference.outputs.ref }}
