name: Lint and test on runner

on:
  pull_request:
    branches:
    - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Access repo at $GITHUB_WORKSPACE
      - uses: actions/checkout@v2.3.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5

      - name: Install dependencies
        run: |
          npx playwright install-deps
          npm ci

      - name: Lint and test sources
        run: |
          npm run lint
          npm run test

      - name: Basic code coverage report
        uses: manarbenkraouda/lcov-reporter-action@v0.3.5.3
        with:
          github-token: ${{ github.token }}
